name: Matthew Vella
favicon: null
layout_spectrum: 0.9315585698932409
typography_spectrum: 0.9519794315565377
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.19121835916303098
  lightness: 0.7400898633059114
  saturation: 0.7272247201763093
  rhythmicContrast: 0.9554686893243343
purpose: []
